version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i
  build:
    commands:
      - export NODE_ENV=production
      - npm run build
  post_build:
    commands:
      - aws s3 sync . s3://hmp-ordering.com --exclude "*" --include "build/*"
      - echo "Copying files to s3 ......."
      - aws s3 cp   s3://hmp-ordering.com/build/ s3://hmp-ordering.com/ --recursive --metadata-directive REPLACE --cache-control max-age=604800,s-maxage=604800
artifacts:
  files:
    - '**/*'
